branches:
    only:
        - master

language: objective-c

xcode_workspace: Demo.xcworkspace
xcode_project: Demo.xcodeproj
xcode_scheme: DemoObjC

script: xctool -workspace Demo.xcworkspace -scheme DemoObjC -sdk iphonesimulator
